# GitBook configuration for Starknode Kit documentation

root: ./
structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - search
  - sharing
  - fontsettings
  - highlight
  - livereload
  - expandable-chapters
  - anchors
  - github
  - edit-link
  - copy-code-button

pluginsConfig:
  github:
    url: https://github.com/thebuidl-grid/starknode-kit
  edit-link:
    base: https://github.com/thebuidl-grid/starknode-kit/edit/main/docs
    label: Edit This Page
  sharing:
    facebook: false
    twitter: true
    google: false
    weibo: false
    instapaper: false
    vk: false
    all:
      - twitter
      - linkedin
